FROM mcr.microsoft.com/dotnet/sdk:8.0 

WORKDIR /src 

COPY ./APIAssinaturaBarbearia/APIAssinaturaBarbearia.sln ./APIAssinaturaBarbearia/

COPY ./APIAssinaturaBarbearia/APIAssinaturaBarbearia/APIAssinaturaBarbearia.csproj ./APIAssinaturaBarbearia/APIAssinaturaBarbearia/
COPY ./APIAssinaturaBarbearia/APIAssinaturaBarbearia.Domain/APIAssinaturaBarbearia.Domain.csproj ./APIAssinaturaBarbearia/APIAssinaturaBarbearia.Domain/
COPY ./APIAssinaturaBarbearia/APIAssinaturaBarbearia.Application/APIAssinaturaBarbearia.Application.csproj ./APIAssinaturaBarbearia/APIAssinaturaBarbearia.Application/
COPY ./APIAssinaturaBarbearia/APIAssinaturaBarbearia.Infrastructure/APIAssinaturaBarbearia.Infrastructure.csproj ./APIAssinaturaBarbearia/APIAssinaturaBarbearia.Infrastructure/
COPY ./APIAssinaturaBarbearia/APIAssinaturaBarbearia.CrossCutting/APIAssinaturaBarbearia.CrossCutting.csproj ./APIAssinaturaBarbearia/APIAssinaturaBarbearia.CrossCutting/
COPY ./APIAssinaturaBarbearia/TestesAPI/TestesAPI.csproj ./APIAssinaturaBarbearia/TestesAPI/

RUN dotnet restore ./APIAssinaturaBarbearia/APIAssinaturaBarbearia.sln

COPY . .

EXPOSE 8080

CMD ["dotnet", "watch", "run", "--project", "./APIAssinaturaBarbearia/APIAssinaturaBarbearia/APIAssinaturaBarbearia.csproj", "--urls", "http://0.0.0.0:8080"]