services:
  apidev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: apidev
    ports:
      - "5000:8080"
    depends_on:
      - "sqlserver"
    networks:
      - redeapi
    volumes:
      - "./:/src" 

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=Senha123"
    volumes:
      - "sqldata:/var/opt/mssql"
    ports:
      - "1433:1433"
    networks:
      - redeapi

volumes:
  sqldata:

networks:
  redeapi:
    driver: bridge
