services:
    api:
        build: 
            context: . 
            dockerfile: Dockerfile
        container_name: api
        ports:
            - "5000:8080"
        depends_on:
            - "sqlserver"
        networks:
            redeapi:
        
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: sqlserver
        environment:
            - "ACCEPT_EULA=Y"
            - "MSSQL_SA_PASSWORD=Morango578"
        ports:
            - "1433:1433"
        networks:
            redeapi:
        volumes:
            - "sqldata:/var/opt/mssql"

volumes:
    sqldata:

networks:
    redeapi:
        driver: bridge